# Generated by Django 5.2 on 2025-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_payment_claim_remove_insurance_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='reason',
        ),
        migrations.AddField(
            model_name='encounter',
            name='procedures',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
