# Generated by Django 5.2 on 2025-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_encounter_notes_encounter_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='reason',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('phone', 'Phone'), ('telehealth', 'Telehealth'), ('other', 'Other')], max_length=100),
        ),
    ]
