# Generated by Django 5.2 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='notes',
        ),
        migrations.AddField(
            model_name='encounter',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
