# Generated by Django 5.2.1 on 2025-06-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_provider_user_alter_appointment_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(blank=True, help_text="Select a doctor (must be a user in the 'Doctor' group)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
